### ISSUE TITLE
Twitter links are no longer redirected in Chromium

### ISSUE THREAD

**Issue by tux93** [SimonBrazell/privacy-redirect#104]
In the dev tools console I see this error:   
```
Error handling response: TypeError: Cannot read property 'host' of undefined
    at shouldRedirect (chrome-extension://pmcmeagblkinmogikoikkdjiligflglb/assets/javascript/remove-twitter-sw.js:39:9)
    at chrome-extension://pmcmeagblkinmogikoikkdjiligflglb/assets/javascript/remove-twitter-sw.js:84:11
remove-twitter-sw.js:79 Unregistered Twitter SW ServiceWorkerRegistration
```

Plugin version is 1.1.41, chromium version 85.0.4183.102

**Comment by SimonBrazell** [comment]
Hi @tux93 this must be related to a recent change I made to nitter instances, I'll fix it up in the next release.
